### PR TITLE
split optimization run into subfunctions and implemented 90-10 split

### PR DESCRIPTION
**Pull request by aranas**
Okay, I tried my best to split the optimization run function, not sure if I succeeded :)
Some remarks:
1. For now the script creates a 90-10 split by actually dividing the data according to the indexes given by StratifiedShuffleSplit. In the crossvalidation folds I use indexing only. Is there a way to index and indexed array?? Because this would save lines 355-358.

2. I thought it was a good idea to create the bookkeeping function which writes results to files. I think this might be better called in the main() function, what do you think?

3. Not sure how compatible StratifiedShuffleSplit is with Lilo. I did not know how to check for the functionality in older packages, but probably this has to be adjusted for the different python versions as well.

### CODE REVIEW

**Comment by twesterhout** [comment]
Well, it looks like you made `optimization_run` even more ugly ;)

A few comments about the design.

The global _90-10-split-algorithm_ is more or less the following, right?
```python
def global_90_10_algo(all_data):
    idx_90, idx_10 = split(all_data)
    run_a_couple_of_folds(all_data[idx_90]) # uses run_one_fold under the hood
    if test_on_10:
        run_one_fold(all_data[idx_90], all_data[idx_10])
```
This allows you to split `optimization_run` into at least three parts. `split`-part would do more or less what lines [352-359](https://github.com/mlp2018/BagofWords/pull/27/commits/5752b97dd66ae1b501046af68c97b35d8d8d5655#diff-4e4ef7d723e69ad47c157bfb8f09a9d5R352) are doing; `run_one_fold` would replace lines [396-403](https://github.com/mlp2018/BagofWords/pull/27/commits/5752b97dd66ae1b501046af68c97b35d8d8d5655#diff-4e4ef7d723e69ad47c157bfb8f09a9d5R396); `run_a_couple_of_folds` would replace the [huge if](https://github.com/mlp2018/BagofWords/pull/27/commits/5752b97dd66ae1b501046af68c97b35d8d8d5655#diff-4e4ef7d723e69ad47c157bfb8f09a9d5R365). What do you think?

Or, to be a bit more concrete, I would suggest the following:
```python
def split_90_10(data: Tuple[np.ndarray, np.ndarray], conf) \
    -> Tuple[np.ndarray, np.ndarray]:
    pass

def run_one_fold(train_data: Tuple[np.ndarray, np.ndarray],
                 test_data: Tuple[np.ndarray, np.ndarray],
                 mk_vectorizer, mk_classifier) \
    -> Tuple[float, np.ndarray]: # i.e. score + indices of wrong predictions
    pass

def run_a_couple_of_folds(data: Tuple[np.ndarray, np.ndarray],
                          conf, mk_vectorizer, mk_classifier) \
    -> Tuple[float, float, np.ndarray]: # i.e. score +/- stddev and wrong predictions' indices
    pass
```
where the implementation is left as an exercise :)


And not to your questions:
1. Sure, how about
```python
data = array([1, -2, 8, 6, -20, 2])
indices = array([2, 3, 4])
indices_of_indices = array([0, 2])
print(data[indices[indices_of_indices]])
# ---> [8 -20]
```
2. I'm OK with having a book keeping function. Calling it from main is, in principle, also fine (if calling it requires no additional data manipulations).
3. Don't worry about that for now. We'll fix it afterwards.

**Comment by aranas** [comment]
I see the value in creating a run_one_fold function. Does it then make more sense to have this be an inner function, as you had it with the "go" before, since it is not really a coherent module but combines several operations and is mostly for reasons of "keeping it dry"?
If we do the double indexing (cool that this is possible btw) then I think we don't need a separate split part as we could code it something like this:
``` python
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
    
for global_train_index, global_test_index in sss.split(reviews, sentiments):
        skf = StratifiedKFold( n_splits=n_splits, random_state=5, shuffle=True)
            
        for idx, (train_index, test_index) \
                in enumerate(skf.split(reviews[global_train_index], sentiments[global_train_index])):
               run_one_fold(idx, reviews[global_train_index[train_index]],
                            sentiments[global_train_index[train_index]])
``` 
And concerning the run_a_cuple_of_folds(), you are suggesting to have this function contain the if clause. Is this really necessary? Because with run_one_fold in place it would then only contain the two different StratifiedKFold calls and the call to run_one_fold. What is the difference to simply having these lines in the optimization_run function directly?

**Comment by twesterhout** [comment]
The main reasons are clarity and extensibility. I'm afraid when you add all the extra `loggin.info` calls and lilo5 compatibility stuff (I've just checked and we need to handle `StratifiedShuffleSplit` in a way similar to `StratifiedKFold`, i.e. another `if`) the function will explode... I propose a deal: if you manage to fit all this in, say, 30 lines of (readable) code, we leave it be, otherwise, we split it into small (5-10 line long) functions. Does that sound fair?

**Comment by aranas** [comment]
Okay, I see if we have to if-clause more things for lilo compatibility, it might make sense indeed. I did it as @twesterhout suggested now. The bookkeeping function gave me a headache. If anyone wants to create it feel free, for now I took it out again.

Let me know if this is a better solution now or if there are any further suggestions. I guess the code doesn't need to be perfect now, we can adjust it later as we go along optimising the classification itself.

**Comment by twesterhout** [comment]
Alright, I do like this one better. There are still a few small things I'm not happy about.
* Passing `conf` argument to inner functions. Let's not do that. `conf` was meant as a simple implementation of configuration options/command line parameters. It's not meant to be used as a global variable. So `optimization_run` is as far as `conf` should be propagated. `run_a_couple_of_folds` only needs two arguments, not the whole `conf`; `split_90_10` doesn't need `conf` at all (also see next bullet).
* Why is 10% hard-coded? It should be really easy to make it configurable (then `split_90_10` does need `conf`, but again, only a small part of it)
* The `data` argument. I suppose you picked it from my examples above. Parameter names there weren't a suggestion, sorry, they were meant to help understand the examples. Alternatively, we can keep the `data`, but then please add type annotations and/or doc strings.
* There's a [Python style guide (PEP8)](https://www.python.org/dev/peps/pep-0008/). Any chance we could try to follow it? There's a tool called [pylint](https://pypi.python.org/pypi/pylint) which complains when you do stuff not the PEP8's way. It ensures consistency, which is nice when working as a teem. @johannadevos maybe you can step in, how was your experience with pylint?

**Comment by ghost** [comment]
Hey there, I see a lot of good work has been done! Since Tom checked already everything, is it okay if we leave it at that, or is there anything that me and the other should specifically look at?

@twesterhout I didn't use pylint yet (it's on my to-do list), but it definitely seems a good idea to me to apply it to our code.

**Comment by aranas** [comment]
I did not know pylint, but it sounds like a good idea to me! @twesterhout it is probably easiest if you just change the things you are not happy about yourself and then we could merge this. It seems to be only minor style changes which you are concerned about, so should be a quick fix for you.

**Pull request merged**
